id: configmap
name: ConfigMap
full-link: /docs/tasks/configure-pod-container/configure-pod-configmap/
related:
- pod
- secret
tags:
- core-object
short-description: >
  An API object used to store non-confidential data in key-value pairs. Can be consumed as environment variables, command-line arguments, or config files in a volume.
long-description: >
  Allows you to decouple environment-specific configuration from your container images, so that your applications are easily portable.
  When storing confidential data use a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/).
